version: '3'

services:
  web:
    build: .
    container_name: webserver
    volumes:
      - ./WEB_ROOT/site1:/var/www/site1
      - ./WEB_ROOT/site2:/var/www/site2
      - ./apache_config.conf:/etc/apache2/sites-available/000-default.conf
      - ./certfile.cer:/etc/apache2/ssl/certfile.cer
      - ./keystore.jks:/etc/apache2/ssl/keystore.jks
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.site1.rule=Host(`site1.local`)"
      - "traefik.http.routers.site1.entrypoints=web"
      - "traefik.http.services.site1.loadbalancer.server.port=80"
      - "traefik.http.routers.site1.service=site1"
      - "traefik.http.routers.site1-secure.rule=Host(`site1.local`)"
      - "traefik.http.routers.site1-secure.entrypoints=websecure"
      - "traefik.http.routers.site1-secure.tls=true"
      - "traefik.http.services.site1-secure.loadbalancer.server.port=443"
      - "traefik.http.routers.site1-secure.service=site1"
      - "traefik.http.routers.site2.rule=Host(`site2.local`)"
      - "traefik.http.routers.site2.entrypoints=web"
      - "traefik.http.services.site2.loadbalancer.server.port=80"
      - "traefik.http.routers.site2.service=site2"
      - "traefik.http.routers.site2-secure.rule=Host(`site2.local`)"
      - "traefik.http.routers.site2-secure.entrypoints=websecure"
      - "traefik.http.routers.site2-secure.tls=true"
      - "traefik.http.services.site2-secure.loadbalancer.server.port=443"
      - "traefik.http.routers.site2-secure.service=site2"
    networks:
      - webnet

  traefik:
    image: traefik:v2.4
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - webnet

networks:
  webnet:
