version: '3'
services:
  web:
    image: your-apache-php-image
    container_name: webserver
    volumes:
      - ./WEB_ROOT/site1:/var/www/site1
      - ./WEB_ROOT/site2:/var/www/site2
      - ./apache_config.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "80:80"
    networks:
      - webnet

networks:
  webnet:
